export const pricingListData = [
  {
    id: 'seo_smaller',
    type: 'Smaller',
    price: '₹ 75,000 / Year + 18% GST',
    amount: 75000,
    priceList: [
      '10 Keywords',
      '1 Year',
      '60% keywords top 10 Guarantee',
      '20+ Directory Submissions',
      '30+ Social Bookmarking',
      '3+ Article Submission',
      '3+ Press Release Submission',
      'ONPAGE OPTIMIZATION',
      'Google Analytics Installation',
      'Google Webmaster Installation',
      'Title Tag Optimization',
      'Meta Description Optimization',
      'Keyword Optimization',
      'Body Text Optimization',
      'Alt Tag Optimization',
      'Sitemap Implementation',
      'Robot.txt Implementation',
      'Monthly Report',
      'Contact: Email/Chat/Phone',
    ],
  },
  {
    id: 'seo_small',
    type: 'Small',
    price: '₹ 8,000 / Month + 18% GST',
    amount: 8000,
    priceList: [
      '10 Keywords',
      'Per Months',
      '80% keywords top 10 Guarantee',
      '30 Directory Submissions',
      '50 Social Bookmarking',
      '5 Article Submission',
      '5 Press Release',
      '1+ Blog',
      '15+ blog submission/Month',
      '5+ PPT Submission/Month',
      '5+ Classified Submission',
      'ONPAGE OPTIMIZATION',
      'Title Tag Optimization',
      'Meta Description Optimization',
      'Keyword Optimization',
      'Canonicalization',
      'Website Page Load Optimization',
      'HTML Code Cleanup & Optimization',
      'Internal link structuring & optimization',
      'Image & Hyperlink Optimization',
      'Robots.txt Creation/Analysis',
      'HTML & XML Sitemap',
      'Google & Bing Webmaster Tools',
      'Google Analytics',
      'Monthly Report',
      'Contact: Email/Chat/Phone',
    ],
  },
  {
    id: 'seo_medium',
    type: 'Medium',
    price: '₹ 14,000 / Month + 18% GST',
    amount: 14000,
    priceList: [
      '20 Keywords',
      'Per Month',
      '80% keywords top 10 Guarantee',
      '60 Directory Submissions',
      '100 Social Bookmarking',
      '10 Article Submission',
      '10 Press Release Submission',
      '5 forum profile creation/Month',
      '2+ Blog',
      '30+ blog submission/Month',
      '10+ PPT Submission/Month',
      '10+ Classified Submission',
      'Doc Submission on Sites like scribd.com,issuu.com',
      'ONPAGE OPTIMIZATION',
      'Google Analytics Installation',
      'Google Webmaster Installation',
      'Title Tag Optimization',
      'Meta Description Optimization',
      'Keyword Optimization',
      'Body Text Optimization',
      'Alt Tag Optimization',
      'Sitemap Implementation',
      'Robot.txt Implementation',
      'Canonicalization',
      'Website Page Load Optimization',
      'HTML Code Cleanup & Optimization',
      'Internal link structuring & optimization',
      'SOCIAL MEDIA OPTIMIZATION',
      'Google+ Business Page Creation',
      'Facebook Fan Page Creation',
      'Twitter Account Creation',
      'Video Optimization',
      'YouTube Channel Creation',
      'Monthly Report',
      'Contact: Email/Chat/Phone',
    ],
  },
  {
    id: 'seo_business',
    type: 'Business',
    price: '₹ 20,000 / Month + 18% GST',
    amount: 20000,
    priceList: [
      '30 Keywords',
      'Per Month',
      '80% keywords top 10 Guarantee',
      '80+ Directory Submissions',
      '150+ Social Bookmarking',
      '20+ Article Submission',
      '20+ Press Release Submission',
      '2+ Guest Post',
      '10 forum profile creation/Month',
      '3+ Blog',
      '50+ blog submission/Month',
      '15+ PPT Submission/Month',
      '20+ Classified Submission',
      '5+ PDF Submission/Month',
      'Doc Submission on Sites like scribd.com,issuu.com',
      'ONPAGE OPTIMIZATION',
      'Google Analytics Installation',
      'Google Webmaster Installation',
      'Title Tag Optimization',
      'Meta Description Optimization',
      'Keyword Optimization',
      'Body Text Optimization',
      'Alt Tag Optimization',
      'Sitemap Implementation',
      'Robot.txt Implementation',
      'Canonicalization',
      'Website Page Load Optimization',
      'HTML Code Cleanup & Optimization',
      'Internal link structuring & optimization',
      'SOCIAL MEDIA OPTIMIZATION',
      'Google+ Business Page Creation',
      'Facebook Fan Page Creation',
      'Twitter Account Creation',
      'Video Optimization',
      'YouTube Channel Creation',
      'Monthly Report',
      'Contact: Email/Chat/Phone',
    ],
  },
];
